# 站点设置
标题:风清扬博客
SEO标题:风清扬的博客|
header-img     : img/home-bg.jpg
电子邮件： wyfwzx621@gmail.com
描述: "这里是风清扬的个人博客，与你一起发现更大的世界 | "
关键词: " 风清扬、Hux Blog、博客、个人网站、互联网、电影、音乐、电视软件、React Native、破解、软件"
url       : "https://huangxuan.me"          #你的主机，绝对URL
基本网址：“”         # 例如，如果您的博客托管在 'host/blog' 上，则为 '/blog'

# 发布标记未来日期的帖子或集合文档。
未来：真实



# 构建设置
# 从 2016 年开始，GitHub Pages 不再支持“pygments”。使用“胭脂”来突出显示。
荧光笔：rouge
永久链接：漂亮
分页：10
排除：
  [
    “不见的”，
    “节点模块”，
    “Gruntfile.js”，
    “包.json”，
    “自述文件.md”，
    "README.zh.md"        ,
  ]
关键点：正确#如果你想自定义一个点。查看 `post.html` 的第 181 行
#如果您遇到中国遇到时区问题（例如#68），请使用此处取消注释：
#时区：CN

# 宝石
# 从 PR#40 开始，支持 Jekyll 3.0 的本地预览
#确定你已经安装了这个 gem
# `$ gem install jekyll-paginate`
插件：[ jekyll-paginate ]       ]

#降价设置
# 将 redcarpet 替换为 kramdown，
# 虽然redcarpet可以自动高亮代码，但是缺少header-id导致无法编目，所以我改用kramdown
# 文档：http://jekyllrb.com/docs/configuration/#kramdown
markdown  :降价：克拉姆唐
克拉姆当：
  输入： 输入：GFM       # 使用 Github Flavored Markdown ！ 重要
  语法突出显示选项：
    跨度：
      行号：假
    淤泥：
      行号：true
      起始行：1

#Disqus设置
disqus_用户名：disqus_用户名：hux

#网易设置
网易评论：假

# 分析设置
# 百度分析
# ba_track_id: [你的曲目 ID]

# 谷歌分析
ga_track_id ：“UA-49627206-1”     # 格式：UA-xxxxxx-xx
ga_域：huangxuan.me

# 侧边栏设置
sidebar  :: true # 是否使用侧边栏。: true # 是否使用侧边栏。
sidebar-about-descriptionsidebar-about-description  : “做一个有赃物的财务 <br> React Team @ Meta” : “做一个有赃物的财务 <br> React Team @ Meta”
侧边栏头像： https侧边栏头像：https://github.com/Huxpro.png#使用绝对URL，在 `/` 和 `/about/` 中都使用了: //github.com/Huxpro. png#使用绝对URL，在`/`和`/about/`中都使用了

# Featured Tags
featured-tags: feature-tags: true # 是否使用Feature-Tags# whether or not using Feature-Tags
featured-condition-size: featured-condition-size: 1 # 如果标签的大小大于此条件值，则该标签将被推荐

# Progressive Web Apps
chrome-tab-theme-color: "#000000"
service-worker: true

# MathJax rendering for layout:page (e.g. post preview)
page-mathjax: false

# Friends
friends:
  [[
    { title: "乱序（Midare）"    { title: "乱序（Midare）", href: "http://mida.re/" },: "http://mida.re/" },
    { title: "Ebn Zhang"    { title: "Ebn 张", href: "https://ebnbin.dev/" },: "https://ebnbin.dev/" },
    { title: "Kun Qian"    { title: "坤谦", href: "http://kunq.me" },: "http://kunq.me" },
    { title: "Sherry Woo"    { title: "Sherry Woo", href: "https://sherrywoo.me/" },: "https://sherrywoo.me/" },
    { title: "SmdCn"    { title: "SmdCn", href: "http://blog.smdcn.net" },: "http://blog.smdcn.net" },
    { title: "JiyinYiyong"    { title: "JiyinYiyong", href: "http://tiye.me/" },: "http://tiye.me/" },
    { title: "DHong Say"    { title: "Dhong Say", href: "http://dhong.co" },: "http://dhong.co" },
    { title: "尹峰以为"    { title: "尹峰以为", href: "http://ingf.github.io/" },: "http://ingf.github.io/" },
  ]]
